// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTNuS2a2cmQiQEthS4AU17JID2U_wiMTA',
    appId: '1:628206724834:web:710ddff1845bb9838420bb',
    messagingSenderId: '628206724834',
    projectId: 'spotify-flutter-app-70cb7',
    authDomain: 'spotify-flutter-app-70cb7.firebaseapp.com',
    storageBucket: 'spotify-flutter-app-70cb7.appspot.com',
    measurementId: 'G-DLMCSZKCM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjrAvsggUu4saboKfnfoHrMJTCLem5v4g',
    appId: '1:628206724834:android:9119155beedeed338420bb',
    messagingSenderId: '628206724834',
    projectId: 'spotify-flutter-app-70cb7',
    storageBucket: 'spotify-flutter-app-70cb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGNXFdeVUw64sehy_Lkte176LXnq2_9BE',
    appId: '1:628206724834:ios:0d37650173b10fd88420bb',
    messagingSenderId: '628206724834',
    projectId: 'spotify-flutter-app-70cb7',
    storageBucket: 'spotify-flutter-app-70cb7.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGNXFdeVUw64sehy_Lkte176LXnq2_9BE',
    appId: '1:628206724834:ios:0d37650173b10fd88420bb',
    messagingSenderId: '628206724834',
    projectId: 'spotify-flutter-app-70cb7',
    storageBucket: 'spotify-flutter-app-70cb7.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTNuS2a2cmQiQEthS4AU17JID2U_wiMTA',
    appId: '1:628206724834:web:7521777cdf2728538420bb',
    messagingSenderId: '628206724834',
    projectId: 'spotify-flutter-app-70cb7',
    authDomain: 'spotify-flutter-app-70cb7.firebaseapp.com',
    storageBucket: 'spotify-flutter-app-70cb7.appspot.com',
    measurementId: 'G-F73XKZW1F1',
  );
}
